### PR TITLE
Report ambiguous syscfg configuration

### PR DESCRIPTION
**Pull request by m-gorecki**
This addresses: https://github.com/apache/mynewt-newt/issues/565

### CODE REVIEW

**Review by sjanc — APPROVED** [review]

**Comment by sjanc** [comment]
would be good to also add unit test that will validate this before closing issue

**Review by sjanc — COMMENTED** [review]
this also needs to validate if value differs as it is fine to set it to same value from multiple locations

**Comment by sjanc** [comment]
seems to be crashing on specific target
https://github.com/apache/mynewt-nimble/actions/runs/10739293391/job/29840180220?pr=1851

(can be reproduced with .github/nordic_pca10028_blehci target from nimble repo)

**Comment by m-gorecki** [comment]
This should fix the issue: https://github.com/apache/mynewt-newt/pull/570

**Pull request merged**
