### PR TITLE
newt: Add external repos patches support

### PR DESCRIPTION
**Pull request by m-gorecki**
Now if package that adds external repository contains directory patches/*external_repo_name*, newt will try to apply patches inside this directory to the external repo.

### CODE REVIEW

**Review by kasjer — APPROVED** [review]
Tested OK.

Check fails because code tries to commit (apply patches) without settings git user.name user.email

**Review by sjanc — CHANGES_REQUESTED** [review]
I think we should use GIT_COMMITTER_NAME and GIT_COMMITTER_EMAIL to avoid requiring git configuration by user. Also this would allow us to have 'newt' as committer ie:
GIT_COMMITTER_NAME=newt
GIT_COMMITTER_EMAIL=dev@mynewt.apache.org

**Review by sjanc — APPROVED** [review]

**Comment by kasjer** [comment]
When patch fails affected git repository stays in state that `git am --abort` or `git am --skip` are required. Maybe newt could call `git am --abort` as not to leave git in the middle of git am session

**Comment by kasjer** [comment]
Verified to work

**Pull request merged**
