### PR TITLE
Mcuboot hack to prevent `newt upgrade` failure

### PR DESCRIPTION
**Pull request by ccollins476ad**
For projects using mcuboot, `newt upgrade` has been failing.  The error message is:
```
Error: Error updating "mcuboot": error: The following untracked working
tree files would be overwritten by checkout:
        ext/mbedtls/include/mbedtls/asn1.h
        ext/mbedtls/include/mbedtls/bignum.h
        ext/mbedtls/include/mbedtls/check_config.h
        ext/mbedtls/include/mbedtls/config.h
        ext/mbedtls/include/mbedtls/ecdsa.h
        ext/mbedtls/include/mbedtls/ecp.h
        ext/mbedtls/include/mbedtls/md.h
        ext/mbedtls/include/mbedtls/oid.h
        ext/mbedtls/include/mbedtls/pk.h
        ext/mbedtls/include/mbedtls/platform.h
        ext/mbedtls/include/mbedtls/platform_util.h
        ext/mbedtls/include/mbedtls/threading.h
Please move or remove them before you switch branches.
Aborting
```
The problem is caused by a recent change to mcuboot - a normal directory was replaced with a submodule.  Git is unable to transition from a post-replace commit to a pre-replace commit because some files in the submodule used to exist in the mcuboot repo itself.

This commit implements a pair of hacks to workaround this problem.  Upon performing a checkout operation on the mcuboot repo:

1. If newt detects the above error message, it removes the `ext/mbedtls` directory and tries again.

2. If newt detects a different warning message (`unable to rmdir 'sim/mcuboot-sys/mbedtls': Directory not empty`), it removes `sim/mcuboot-sys/mbedtls`.

The second hack is required when transitioning from pre-replace to post-replace.  In this case, the checkout operation succeeds, but an orphaned directory is left behind, making the repo look dirty.

This is expected to be a short-term fix.  When we have a general fix for this issue, this hack can be removed.

### CODE REVIEW

**Comment by utzig** [comment]
Tested locally, works well!

**Comment by kazmer97** [comment]
Hi,
I am new to the newt environment. What should I do exactly to get the `newt upgrade` command working now?

**Comment by utzig** [comment]
@kazmer97 It might depend on how you installed `newt` before, but `go get -u github.com/apache/mynewt-newt/newt` should work.

**Comment by kazmer97** [comment]
> @kazmer97 It might depend on how you installed `newt` before, but `go get -u github.com/apache/mynewt-newt/newt` should work.

Thanks for the quick reply. 

I've installed `Newt`  through `brew` following the native installation documentation from the website. (on a macbook pro 2015, running OSX catalina)

I don't seem to find the repo mentioned by you.  Should I try installing Newt from the source?

**Comment by utzig** [comment]
> I've installed Newt through brew following the native installation documentation from the website. (on a macbook pro 2015, running OSX catalina)

Try: `brew install --HEAD mynewt-newt`

**Comment by kazmer97** [comment]
> > I've installed Newt through brew following the native installation documentation from the website. (on a macbook pro 2015, running OSX catalina)
> 
> Try: `brew install --HEAD mynewt-newt`

Thank you, this solved it. Appreciate the help.

**Comment by gigi81** [comment]
I'm getting the same error on Linux. I installed with apt-get. Should I build it from the source instead?
I'm following the quick start guide and I have to say this is very confusing as you are thinking you are doing something wrong. You don't think it is an actual bug...

**Comment by ccollins476ad** [comment]
@gigi81 Yes, I'm afraid you'll have to build from source until we release a new version of newt.  You can build newt using the following steps (this is untested; I don't have a Debian / Ubuntu distro to test with at the moment):

1. Uninstall the old version of newt:
```
sudo apt remove mynewt-newt
```

2. Install Go (I'm assuming this gives you a recent enough version):
```
sudo apt install golang-go
```

3. Install newt:
```
go get mynewt.apache.org/newt/newt
```

**Comment by Thilanka97** [comment]
Hey @ccollins476ad,
I am getting the same error. I am new to mynewt. I am using newt on windows 10. what exactly should I do to fix this? 

acuboot version

Does this mean that I have mcuboot 1.3.1 and the project has version 1.5.0 ? Is this a problem with the mcuboot version ? will installing the mcuboot 1.5.0 version work ? or what should I do ? 

Thanks in advance !

**Comment by utzig** [comment]
@Thilanka97 You should upgrade `newt` to a version that includes a "hack" to remove this directory, the issue is not related to the mcuboot version but due to moving submodules inside the repo. Removing `ext/mbedtls` manually should also work afair.

**Pull request merged**
